"""migrate

Revision ID: 5c45d06877ee
Revises: 
Create Date: 2017-06-12 14:10:06.281333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c45d06877ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('act_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('act_name', sa.String(length=50), nullable=True),
    sa.Column('act_hex', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('act_id')
    )
    op.create_table('group',
    sa.Column('g_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('g_name', sa.String(length=50), nullable=True),
    sa.Column('g_hex', mysql.INTEGER(unsigned=True), nullable=True),
    sa.PrimaryKeyConstraint('g_id')
    )
    op.create_table('user',
    sa.Column('u_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('g_id', mysql.INTEGER(unsigned=True), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('passwd', sa.String(length=32), nullable=False),
    sa.Column('phonenum', sa.String(length=12), nullable=True),
    sa.Column('image_url', sa.String(length=200), nullable=True),
    sa.Column('aboutme', sa.String(length=500), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('u_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('article',
    sa.Column('arti_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('u_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('read_num', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('uptime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('arti_id')
    )
    op.create_table('follow',
    sa.Column('f_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('u_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('follow_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.ForeignKeyConstraint(['follow_id'], ['user.u_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('f_id')
    )
    op.create_table('secret_msg',
    sa.Column('msg_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('from_user', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('to_user', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('msg_content', sa.Text(), nullable=False),
    sa.Column('msg_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['from_user'], ['user.u_id'], ),
    sa.ForeignKeyConstraint(['to_user'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('msg_id')
    )
    op.create_table('comment',
    sa.Column('com_id', mysql.INTEGER(unsigned=True), nullable=False),
    sa.Column('f_com_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('u_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('arti_id', mysql.INTEGER(unsigned=True), nullable=True),
    sa.Column('com_content', sa.Text(), nullable=False),
    sa.Column('com_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['arti_id'], ['article.arti_id'], ),
    sa.ForeignKeyConstraint(['f_com_id'], ['comment.com_id'], ),
    sa.ForeignKeyConstraint(['u_id'], ['user.u_id'], ),
    sa.PrimaryKeyConstraint('com_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    op.drop_table('secret_msg')
    op.drop_table('follow')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('group')
    op.drop_table('action')
    # ### end Alembic commands ###
